### ISSUE TITLE
Loading some liquid content fails

### ISSUE THREAD

**Issue by cam** [culturekings/shopify-shortcodes#3]
Using the code to load the short code in the template doesn't allow for more complex scenarios.

If you have "{% include 'shortcode' load: page.content-handle.content %}" everything works fine, but something like "{% include 'shortcode' load: pages.[product.title].content %}" won't work.

I think having this would be useful so that we can use the short codes in all scenarios.

**Comment by sturple** [comment]
Thank you for your shortcode snippets, however i found a little clitch, if there is something that im doing wrong maybe you can help out, otherwise this is what i found.

In my product.liquid I added the following code  {% include 'shortcode' load: product.description  %}   in place of {{product.description}}   If i put a shortcode in a product it displays the product.description, if no shortcode is present then it doesn't show any content.
This fails because of this statement {% if shortcodeBegins.size > 1 %} in shortcode.liquid,

 if you put an {% else %}{{loadnew}}{%endif%}} in the shortcode.liquid  it fixed loading the product description that didn't have a shortcode

Thanks
